### ISSUE TITLE
extension can't be installed/enabled

### ISSUE THREAD

**Issue by passivedragon** [Lakshmikanth2001/GitHooks#2]
Searching the marketplace for this extension yields no result, be that via the name, or the full identifier.
Even installing the extension via the .vsix file does not actually seem to install it.

**Comment by Lakshmikanth2001** [comment]
Mention your 
`OS`
`Code Version`

This extension requires `code --version` > `1.72.0`

This link should work well https://marketplace.visualstudio.com/items?itemName=lakshmikanthayyadevara.githooks

**Comment by passivedragon** [comment]
I am using LinuxMint 21, VSCodium 1.73.1 14f2d26367b7e8f03ff2352516ba27d6302dd7b1
In the process of troubleshooting this, I updated VSCodium version (twice actually I think)

I'm not sure what I'm looking at at the moment, I'm fairly confused. I seem to have the extension installed now, playing around with it, it seems to work quite well. However, I still cannot find the extension by searching the builtin extension market, the serach turns up completely blank "no extensions found".
I suppose installing the extension via the extension file manuall did the trick.
A very odd case, I've never encountered this before.

**Comment by Lakshmikanth2001** [comment]
I think, your issue is resolved 

please give your valuable feedback and rating for this extension in `vscode marketplace` thanks for reporting this issue
