### ISSUE TITLE
Building Regex for file path inside `./.git/hook` in vscode extension 

### ISSUE THREAD

**Issue by Lakshmikanth2001** [Lakshmikanth2001/GitHooks#5]
- Current `Regex` just verifies whether `.git` and `hook` both are present in path or not which not an accurate way to tell whether file belongs to `./git/hook` this path 
``` 
"editor/title": [
				{
					"when": "resourcePath =~ /(?=.*\\.git)(?=.*hooks).*/",
					"command": "git-hooks.runCurrentHook",
					"group": "navigation"
				}
			]
```
Updated this regex to view the `runButton` only inside `.git/hooks` directory

**Comment by 9AMTech** [comment]
I was trying to find the file for this so I can do the whole pull request thing. (New to open source, sorry.) I couldn't find the relevant code, but try this regex.

(\/git\/hook\/)

**Comment by 9AMTech** [comment]
Thanks for the opportunity! I love using regexr. It's the best tool for issues like this! I submitted the pull request w/ the correct regex.

**Comment by Lakshmikanth2001** [comment]
```
"when": "resourcePath =~ /(\/\\.git\/hooks\/)/ || resourcePath =~ /(\\.git\\\\hooks\\\\)/",
```
Final regex which was working for both `mac` and `windows` is this one thank you for your contribution

i want to share small code snippet which can help in in budling regex inside string  ( node.js env )

```
var regexParten = /(git\\hooks\\)/
regexParten.source 
'(\\\\.git\\\\hooks\\\\)'
```
it help when your regex contains string escape characters ,

Thank You for your contribution
