### ISSUE TITLE
GitHooks not checking hooksPath

### ISSUE THREAD

**Issue by DraakUSA** [Lakshmikanth2001/GitHooks#9]
As of Git 2.9.0, you can run 'git config [--set] core.hooksPath <location>' to tell git where the hooks directory is.  By setting at the global or system level, it will affect every repo.  Thus on my system I have done 'git config --global core.hooksPath $HOME/.githooks'.  Now I only have to update one location to maintain my hooks.

Running 'git config [--get] core.hooksPath' will let you see what the value is that will be used (or blank if not set).

However, GitHooks only looks in the local .git/hooks directory.  I consider this a bug, since GitHooks is not usable in this situation.

**Comment by Lakshmikanth2001** [comment]
Thanks for your valuable information, in my next release i.e `0.0.16`  , I will make user to include this feature to set a hooks path for git version > 2.9.0 , i will try to make this change in a week or 2 

once's again thank you so much for pointing out this issue

any code contribution would help me a lot

**Comment by Lakshmikanth2001** [comment]
Thanks a lot for your information on `git config [--set] core.hooksPath`  included this feature in my new release `1.0.0` in commit 2ae17bcefcf26ae357d5ab2ed603c608a3ac0b28 unable to execute command `git config [--set] core.hooksPath`  from extension  as it has to executed from non git directory, will try to implement it future releases once again thank you so much  for you input

**Comment by Lakshmikanth2001** [comment]
expect for the `git config --global core.hooksPath` all other command functionalities are present in latest release `1.2.0` for now i am closing this issue as now you can configure your `hooksDirectory`
